# A name that identifies your app
name: my-app
# A namespace where your app will live
namespace: my-namespace
# An URI for your app Docker image
image: docker.pkg.github.com/my-org/my-repo/my-package
# The version of your app which is available as an image
version: 0.0.1
# A Docker repository secret for pulling your image
imagePullSecret: my-pull-secret-name

# The URL your app should be available on
url: https://my-domain.io
# The port your app listens on
port: 3000

# The environment your app requires
environment:
  MY_VARIABLE: my-value

# Volumes to mount
volumes:
  - /path/to/mount/volume # Requests 1Gi by default
  - /path/to/mount/volume: 24Gi
