apiVersion: v1
kind: Pod
metadata:
  name: debugger
spec:
  containers:
  - image: markeijsermans/debug:kitchen-sink
    name: app
    command: ["/bin/sh", "-c", "sleep 3600"]
      #    volumeMounts:
      #    - mountPath: /data
      #      name: debugger-data
      #
      #  volumes:
      #  - name: debugger-data
      #    persistentVolumeClaim:
      #      claimName: hublinks-data
